library(shiny)
library(bslib)
library(plotly)
library(tidyverse)
library(dplyr)
library(scales)
library(ggthemes)
library(shinythemes)

page_one <- tabPanel(
  "Introduction",
  titlePanel("Introduction"),
  h3("The purpose/importance of the project"),
  p("This project investigates the relationship between climate change, urbanization, and demographics to understand their impact on urban environments. By analyzing historical data on precipitation, temperature, and population from over 200 U.S. cities from 1900 to 2010, we aim to reveal trends essential for sustainable urban development amid climate challenges.
    Climate change shapes our planet and triggers environmental shifts. As cities expand and climate patterns shift, 
    understanding the relationship between urban development and climatic variables is crucial. Rapid city population growth amplifies
    heat zones, alters precipitation patterns, and climate change reversely impacts on urban populations. By examining these
    interactions, we address pressing questions at the intersection of environmental science, urban studies, and public policy. 
    The evidence-based insights aim to inform interventions for sustainable urban futures amidst climate challenges. 
    Enhancing our comprehension of these intricate interactions can guide strategies to mitigate climate risks, improve urban planning, 
    and promote environmental sustainability in metropolitan areas."),
  h3("Main questions"),
  tags$ol(
    tags$li("How do temperature and precipitation patterns correlate with urban population increase over the last century?"),
    tags$li("What demographic/geographic factors influence the vulnerability of urban areas to climate change?"),
    tags$li("How do historical climate trends inform future urban planning and policy decisions?")
  ),
  h3("Introduces the data and explains why it is appropriate and where it came from, providing a URL link to the original sources"),
  p("We will use two datasets in this project to examine the interaction between historical temperature, precipitation, 
    and population data in 210 cities over time. These datasets, collected by reputable academic groups, provide historical data on 
    temperature, precipitation, and population. Analyzing these datasets will help identify trends, vulnerabilities, and hotspots where 
    climate change impacts are most pronounced."),
  p("1.     Dataset of temperature and precipitation in the selected 210 US cities
    https://kilthub.cmu.edu/articles/dataset/Assessment_of_historical_annual_temperature_and_precipitation_indices_change_in_the_U_S_cities/7961012/5
    Yuchuan Lai, David Dzombak, Institution: Carnegie Mellon University
    The dataset assesses regional climate including multiple factors in the 210 cities in United States to lay the groundwork for using the historical climate record to provide regional near-term climate forecasts."),
  p("2. 	United States city populations, 1790-2010
https://github.com/cestastanford/historical-us-city-populations/tree/master
Erik Steiner, Center for Spatial and Textual Analysis, Stanford University; Jason A. Heppler, Department of History and UNO Libraries, University of Nebraska at Omaha
The primary source for this data was a US Census Bureau dataset of ~7500 incorporated cities whose populations surpassed 2500 people at some point in their existence. The dataset is part of The Spatial History Project at Stanford University that utilized visual and spatial methods to reconstruct past landscapes to understand how they were produced, experienced, and ultimately transformed.
"),
  h3("Addresses ethical questions and limitations to consider with this dataset"),
  p("The population data was derived from the US Census Bureau and may not fully represent certain demographic groups, potentially due to limited 
  reach, access or willingness to participate in surveys. Both datasets were collected and generated by scholars at academic institutes,
  ensuring reliability and validation of the sources and methods used. These datasets are extensive, comprising thousands of 
  observations and dozens of features, offering substantial power for analysis and yielding interesting results. However, significant 
  preprocessing work lies ahead. Several challenges are anticipated: 1. Missing Data: Due to the historical nature of the data, 
  originating as far back as the 1700s or 1800s, many older records contain missing data. 2. Removing Duplicates and discrepancies: 
  Over time, cities in the datasets have experienced name and territorial changes, resulting in many duplicates or discrepancies. 3. Standardizing Data: For instance, the dataset comprising temperature and precipitation across 210 cities contains individual 
  files for each city, some of which may have variant formats. 4. Multiple resources: A particularly challenging aspect is that the two 
  datasets stem from independent projects, each using their own set of cities. Consequently, there is non-overlap between some cities 
  in the two datasets. Our initial task is to join and merge these datasets, ensuring alignment of data from the same cities and 
  regions. This enables us to analyze climate change alongside population dynamics within the same locales."),
  tags$img(src="https://cdn.pixabay.com/photo/2016/12/29/10/00/sundet-1938198_1280.jpg", width=500, height=300)
)

page_two <- tabPanel(
  "Population Change and Climate",
  titlePanel("Population Change and Climate"),
  sidebarLayout(
    sidebarPanel(
      p("This section explores the relationship between population change and climate variables.")
    ),
    mainPanel(
      h3("Purpose"),
      p("The primary purpose of the provided code is to create a box plot visualization that tracks population change percentages in U.S. cities from 1900 to 2010, stratified by region and state. This approach allows for a thorough examination of how demographic shifts have unfolded over more than a century, while simultaneously investigating any potential correlations with changes in climate, indicated by alterations in average temperatures."),
      h3("Insights"),
      p("The visualization reveals several key insights:"),
      tags$ul(
        tags$li("**Regional and State Variability**: The faceting by region and further stratification by state uncover nuanced patterns in population dynamics that differ significantly from one region to another. This helps in identifying specific regional growth trends and the potential influence of regional policies or economic conditions."),
        tags$li("**Temperature Correlation**: By using a color gradient to denote temperature changes, the plot suggests a visual correlation between climatic conditions and demographic changes. Warmer colors in areas of significant population increase might imply a relationship between milder climates and urban attractiveness or viability."),
        tags$li("**Identification of Outliers**: The clear marking of outliers highlights cities with exceptional growth or decline, which can be pivotal for case studies or further research into the causes behind such anomalies, be it economic, environmental, or social drivers.")
      ),
      h3("Visualization Type"),
      p("The choice of a box plot for this analysis is highly effective. Box plots are particularly suited for displaying the distribution of data and identifying outliers, making them ideal for examining the range and spread of population changes across multiple categories (regions and states in this case). The addition of color gradients to represent another variable (temperature change) enhances the multi-dimensional analysis without cluttering the visual space, adhering to Tufte’s principle of maximizing data ink. The faceted layout further aids in dissecting complex patterns by breaking down the dataset into digestible segments, each representing a coherent geographical or administrative unit, thus facilitating deeper comparative analysis. This methodological approach ensures that the visualization is not only informative but also intuitive and accessible, supporting a wide range of academic and planning activities."),
      plotOutput("boxplot1")
    )
  )
)

page_three <- tabPanel(
  "Third Page",
  titlePanel("Page 3"), 
  sidebarLayout(
    sidebarPanel(
      selectInput(
        inputId = "color_input",
        label = "Choose a color for the graph" ,
        choices = c("Red", "Blue", "Orange", "Green", "Black", "White", "Purple", "Brown")
      )
    ),
    mainPanel(
      p("This graph shows the temperature change in Astoria, Oregon from the 
      1920s to 2010. The graph displaying the average temperature of Astoria 
      reveals significantly lower temperatures compared to other cities in the 
      United States. The average temperature in Astoria ranges from 45 to 55 
      degrees. Although there is a dip at some point, the temperature has generally
      remained within this range.

The graph below is interactive, allowing you to change the colors to white, red, orange, 
black, etc. You can also zoom into the graph to see different data points in more detail. 
For example, you can zoom into the 1920s to closely examine the temperature changes during 
that period. Additionally, you can zoom into a specific year for a more detailed view.
"),
      plotlyOutput(outputId = "chart_3")
    )
  )
)

page_four <- tabPanel(
  "Fourth Page",
  titlePanel("page 4")
)

page_five <- tabPanel(
  "Conclusion",
  titlePanel("Page 5")
)

ui<-fluidPage(
  theme=shinytheme("cerulean"),
  #shinythemes::themeSelector(),
  navbarPage(
    "Climate and Population Dynamics in 210 U.S. Cities: A 20th Century Review",
    header="    Amen Tassaw; Ava Song; Boyan Jiang; Dong-Hui Chen",
    page_one,
    page_two,
    page_three,
    page_four,
    page_five
  )
)
